// noinspection JSUnusedGlobalSymbols

export * from './index-types';
export * from './index-annotations';
export * from './abstract-format';
export * from './abstract-string-type';
export * from './casts';
export * from './type-format';

import {TypeFormatLike} from "./index-types";
import {TypeFormat} from "./type-format";

export const typeFormat: TypeFormatLike = new TypeFormat();

export const alphaFormat = typeFormat.alpha;
export const alphanumericFormat = typeFormat.alphanumeric;
export const asciiFormat = typeFormat.ascii;
export const base32Format = typeFormat.base32;
export const base58Format = typeFormat.base58;
export const base64Format = typeFormat.base64;
export const bicFormat = typeFormat.bic;
export const byteLengthFormat = typeFormat.byteLength;
export const clazzFormat = typeFormat.clazz;
export const creditCardFormat = typeFormat.creditCard;
export const dataUriFormat = typeFormat.dataUri;
export const datetimeFormat = typeFormat.datetime;
export const decimalFormat = typeFormat.decimal;
export const digitFormat = typeFormat.digit;
export const emailFormat = typeFormat.email;
export const escapeFormat = typeFormat.escape;
export const folderFormat = typeFormat.folder;
export const fqdnFormat = typeFormat.fqdn;
export const hashFormat = typeFormat.hash;
export const hexColorFormat = typeFormat.hexColor;
export const hexadecimalFormat = typeFormat.hexadecimal;
export const hostSchemeFormat = typeFormat.hostScheme;
export const hostFormat = typeFormat.host;
export const ibanFormat = typeFormat.iban;
export const imeiFormat = typeFormat.imei;
export const ipFormat = typeFormat.ip;
export const isoDateFormat = typeFormat.isoDate;
export const isrcFormat = typeFormat.isrc;
export const issnFormat = typeFormat.issn;
export const latLongFormat = typeFormat.latLong;
export const localeDateFormat = typeFormat.localeDate;
export const lowerFormat = typeFormat.lower;
export const macFormat = typeFormat.mac;
export const md5Format = typeFormat.md5;
export const mimeFormat = typeFormat.mime;
export const mongoIdFormat = typeFormat.mongoId;
export const multiByteFormat = typeFormat.multibyte;
export const nanoIdFormat = typeFormat.nanoId;
export const normalizedEmailFormat = typeFormat.normalizedEmail;
export const passportFormat = typeFormat.passport;
export const portFormat = typeFormat.port;
export const regExpFormat = typeFormat.regExp;
export const rgbColorFormat = typeFormat.rgbColor;
export const semVerFormat = typeFormat.semVer;
export const stripLowFormat = typeFormat.stripLow;
export const timeFormat = typeFormat.time;
export const unescapeFormat = typeFormat.unescape;
export const upperFormat = typeFormat.upper;
export const urlFormat = typeFormat.url;
